services:
  wd-os5-exporter:
    image: ghcr.io/fata13rorr/wd-os5-exporter:latest
    container_name: wd-os5-exporter
    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "${EXPORTER_PORT:-8085}:8085"

    volumes:
      - "${SSH_KEY_FILE:-./id_ed25519}:/run/secrets/nas_ssh_key:ro"
