services:
  wd-os5-exporter:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: wd-os5-exporter
    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "${EXPORTER_PORT:-8085}:8085"

    volumes:
      - "${SSH_KEY_FILE:-./nas_ed25519}:/run/secrets/nas_ssh_key:ro"

networks:
  default:
    name: wd-os5-exporter
